version: '3.8'

services:
  n8n:
    build: .
    environment:
      - NODE_ENV=production
      - N8N_RELEASE_TYPE=stable
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n-self-host-production.up.railway.app
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n-self-host-production.up.railway.app
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      - N8N_USER_FOLDER=/home/node/.n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: